name: CI/CD Pipeline for Department Store Management System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0' # Use the required .NET version for the project

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore DepartStoreManagementSystem.sln

      # Build the project
      - name: Build solution
        run: dotnet build DepartStoreManagementSystem.sln --configuration Release --no-restore

      # Run tests (if there are any test projects)
      - name: Run tests
        run: dotnet test DepartStoreManagementSystem.sln --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy to Azure Web App (or any other hosting platform)
      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: '<Your-Azure-Web-App-Name>'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
